#!/bin/bash

# Automated Lucide → SyncFusion e-icons replacement script

declare -A ICON_MAP=(
  ["Calendar"]="e-schedule"
  ["Clock"]="e-time"
  ["AlertTriangle"]="e-warning"
  ["CheckCircle2"]="e-check"
  ["CheckCircle"]="e-check"
  ["Check"]="e-check"
  ["XCircle"]="e-close"
  ["X"]="e-close"
  ["Plus"]="e-plus"
  ["ArrowLeft"]="e-arrow-left"
  ["ArrowRight"]="e-arrow-right"
  ["ChevronRight"]="e-chevron-right"
  ["ChevronLeft"]="e-chevron-left"
  ["ChevronDown"]="e-chevron-down"
  ["ChevronUp"]="e-chevron-up"
  ["User"]="e-user"
  ["Play"]="e-play"
  ["Pause"]="e-pause"
  ["SkipForward"]="e-skip-forward"
  ["TrendingUp"]="e-arrow-up"
  ["TrendingDown"]="e-arrow-down"
  ["Minus"]="e-minus"
  ["Inbox"]="e-inbox"
  ["Archive"]="e-folder"
  ["Folder"]="e-folder"
  ["Target"]="e-target"
  ["Upload"]="e-upload"
  ["FileJson"]="e-file"
  ["FileText"]="e-file"
  ["Coffee"]="e-coffee"
  ["Mail"]="e-mail"
  ["Star"]="e-star"
  ["Loader2"]="e-loader"
  ["Download"]="e-download"
  ["Share"]="e-share"
  ["WifiOff"]="e-wifi-off"
  ["Mic"]="e-mic"
  ["MicOff"]="e-mic-off"
  ["MessageSquare"]="e-comment"
  ["Copy"]="e-copy"
  ["Trash2"]="e-delete"
  ["Trash"]="e-delete"
  ["Zap"]="e-lightning"
  ["Sparkles"]="e-lightning"
  ["DollarSign"]="e-dollar"
  ["Key"]="e-key"
  ["Lock"]="e-lock"
  ["AlertCircle"]="e-alert"
  ["Search"]="e-search"
  ["RefreshCw"]="e-refresh"
  ["Camera"]="e-camera"
  ["Layers"]="e-layer"
  ["Moon"]="e-moon"
  ["Sun"]="e-sun"
  ["LogOut"]="e-logout"
  ["LogIn"]="e-login"
  ["Bell"]="e-bell"
  ["BellOff"]="e-notification-off"
  ["Info"]="e-info"
)

echo "This script shows what WOULD be replaced (dry run)"
echo "Review the mappings and run manually if needed"
echo ""

for lucide in "${!ICON_MAP[@]}"; do
  sficon="${ICON_MAP[$lucide]}"
  echo "$lucide → $sficon"
done
